import {
  userRepository,
  tenantRepository,
  organizationRepository,
  customerRepository,
  expenseRepository,
  itemsRepository,
  invoiceRepository,
} from "../libs/app/repository/mongo";
import { repositoryData, useCaseData } from "../libs/entities/interfaces";
import {
  signupUser_UseCase,
  createTenant_UseCase,
  verifyUser_UseCase,
  findMyTenants_UseCase,
  createOrganization_UseCase,
  createCustomer_UseCase,
  createItem_UseCase,
  getAllCustomers_UseCase,
  getAllItems_UseCase,
  editItem_UseCase,
  createInvoice_UseCase,
  createExpense_UseCase,
  getSingleItems_UseCase,
  editCustomer_UseCase,
  getSingleCustomer_UseCase,
  getInvoiceById_UseCase,
  getAllInvoices_UseCase,
  getAllExpense_UseCase,
  getExpenseById_UseCase,
  editExpense_UseCase,
  getAllRecievables_UseCase,
  editInvoice_UseCase,
  getSalesByCustomer_UseCase,
  getChartData_UseCase,
  getExpensePiChartData_UseCase,
  getSalesByItem_UseCase,
  getSalesTableData_UseCase,
  getInvoiceDetails_UseCase,
  getPendingSales_UseCase,
  getRecievedPayments_UseCase,
  getExpenseDetails_UseCase,
  getExpenseByEachCategory_UseCase
} from "../libs/usecases";

const useCases: useCaseData = {
  signupUser_UseCase,
  getAllRecievables_UseCase,
  createTenant_UseCase,
  verifyUser_UseCase,
  createCustomer_UseCase,
  createItem_UseCase,
  getAllCustomers_UseCase,
  getAllItems_UseCase,
  getSalesByCustomer_UseCase,
  findMyTenants_UseCase,
  createOrganization_UseCase,
  editItem_UseCase,
  getSingleItems_UseCase,
  editCustomer_UseCase,
  getSingleCustomer_UseCase,
  createInvoice_UseCase,
  createExpense_UseCase,
  getInvoiceById_UseCase,
  getAllInvoices_UseCase,
  getAllExpense_UseCase,
  getExpenseById_UseCase,
  getSalesByItem_UseCase,
  editExpense_UseCase,
  editInvoice_UseCase,
  getChartData_UseCase,
  getExpensePiChartData_UseCase,
  getSalesTableData_UseCase,
  getInvoiceDetails_UseCase,
  getPendingSales_UseCase,
  getRecievedPayments_UseCase,
  getExpenseDetails_UseCase,
  getExpenseByEachCategory_UseCase
};

const repository: repositoryData = {
  userRepository,
  tenantRepository,
  organizationRepository,
  customerRepository,
  itemsRepository,
  invoiceRepository,
  expenseRepository,
};

export = {
  useCases,
  repository,
};
