# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: client1-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: client1
#   template:
#     metadata:
#       labels:
#         app: client1
#     spec:
#       containers:
#         - name: client1
#           image: yaserkt786/client1:latest
#           env:
#             #- name: MONGO_URI
#             #  value: "mongodb://tenants-mongo-srv:27017/tenants"
#             # - name: JWT_KEY
#             #   valueFrom:
#             #     secretKeyRef:
#             #       name: jwt-secret
#             #       key: JWT_KEY
#             # - name: NATS_CLIENT1_ID
#             #   valueFrom:
#             #     fieldRef:
#             #       fieldPath: metadata.name

# ---
# apiVersion: v1
# kind: Service
# metadata: 
#   name: client1-srv
# spec: 
#   selector:
#     app: client1
#   ports:
#     - name: client1
#       protocol: TCP
#       port: 3000
#       targetPort: 3000
